- name: Install HAProxy
  apt:
    name: haproxy
    state: present
  when: ansible_os_family == 'Debian'

- name: Install HAProxy
  yum:
    name: haproxy
    state: present
  when: ansible_os_family == 'RedHat'

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

- name: Enable and start HAProxy service
  systemd:
    name: haproxy
    enabled: true
    state: started